# -*- coding:utf-8 -*-
"""
Django settings for seemadmin project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f)irsy(-=jt2=25x3vbuxwv+(!rvl)1!y-9v$_n++-skl4u&(8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorl.thumbnail',

    # 'tinymce',
    # 'mce_filebrowser',

    'apps.seems',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'seemadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seemadmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seemadmin',
        'USER': 'seemanager',
        'PASSWORD': 'seem#manage',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'seem': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seem',
        'USER': 'seem',
        'PASSWORD': 'seem#@!',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
}


DATABASE_ROUTERS = ['db_router.SeemRouter']

TINYMCE_DEFAULT_CONFIG = {
  'file_browser_callback': 'mce_filebrowser'
}

# URL_FILEBROWSER_MEDIA = '/admin-media/filebrowser/'
# FILEBROWSER_URL_TINYMCE = '/media/tinymce/jscripts/tiny_mce/'
#
# TINYMCE_DEFAULT_CONFIG = {
#     'plugins': "table,spellchecker,paste,searchreplace",
#     'theme': "advanced",
#     'theme_advanced_toolbar_location':"top",
#     'cleanup_on_startup': True,
# }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-CN'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# 图片处理
PREFIX_PIC_URL = "7xnvhf.com1.z0.glb.clouddn.com"
QINIU_ACCESS_KEY = 's306sluRQe4-8xUq5q4PxP7akVtnhNyeQ6F80vt2'
QINIU_SECRET_KEY = 'tbfwepbG0Dh5wH5NDj5vuPByG8-zcjbiPq7ure8b'


MEDIA_URL = '/uploads/'
rel = lambda *x: os.path.join(os.path.dirname(os.path.abspath(__file__)), *x)
MEDIA_ROOT = rel('../uploads')
